name: Static-analysis

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 urwid requests python-dateutil
    - name: Analysing the code with pylint and flake8
      run: |
        pylint $(find . -name "*.py" | xargs)
        flake8 --ignore E501 $(find . -name "*.py" | xargs)
